/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary:          '#FF4D6D',
        'primary-dark':   '#E03355',
        'primary-light':  '#FF8FA3',
        'primary-bg':     '#FFF0F3',
        secondary:        '#FFB703',
        'secondary-dark': '#D99E00',
        'secondary-light':'#FFD166',
        'secondary-bg':   '#FFFBEB',
        accent:           '#3A86FF',
        'accent-dark':    '#1D6FDB',
        'accent-light':   '#74AAFF',
        'accent-bg':      '#EFF6FF',
        background:       '#FFF8F0',
        surface:          '#FFFFFF',
        'surface-2':      '#FFF5EC',
        'surface-3':      '#FEF3E2',
        'text-base':      '#1F2937',
        'text-muted':     '#6B7280',
        'text-light':     '#9CA3AF',
        border:           '#E5E7EB',
        'border-light':   '#F3F4F6',
        success:          '#10B981',
        'success-bg':     '#ECFDF5',
        warning:          '#F59E0B',
        'warning-bg':     '#FFFBEB',
        danger:           '#EF4444',
        'danger-bg':      '#FEF2F2',
        info:             '#3B82F6',
        'info-bg':        '#EFF6FF',
      },
      fontFamily: {
        display: ['"Syne"', 'sans-serif'],
        body:    ['"Plus Jakarta Sans"', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
      },
      boxShadow: {
        'card':       '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'card-md':    '0 4px 12px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04)',
        'card-lg':    '0 8px 24px rgba(0,0,0,0.10), 0 4px 8px rgba(0,0,0,0.06)',
        'primary':    '0 4px 14px rgba(255,77,109,0.35)',
        'accent':     '0 4px 14px rgba(58,134,255,0.3)',
      },
      animation: {
        'fade-in':      'fadeIn 0.3s ease-out',
        'slide-up':     'slideUp 0.3s ease-out',
        'slide-in':     'slideIn 0.25s ease-out',
        'pulse-soft':   'pulseSoft 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:     { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp:    { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideIn:    { from: { opacity: '0', transform: 'translateX(-8px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        pulseSoft:  { '0%,100%': { opacity: '1' }, '50%': { opacity: '.6' } },
      },
    },
  },
  plugins: [],
};